#%RAML 1.0
title: Coinnect Standard API
version: v1
baseUri: /coinnect/v1/
mediaType: application/json
/spot-price:
  description: Get current price
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status" : "success",
                "data": { "price": 212}
              }
/send-money:
  post:
    protocols: HTTPS
    description: Send money to user
